

#Books
http://localhost:4004/library/Books?$orderby=ID desc&

###
#book by id
http://localhost:4004/library/Books(1)


###
#Books with authors and categories google
http://localhost:4004/library/Books?$expand=authors($expand=author),categories($expand=category)&$search=kevin&$count=true


###
#Books with authors and categories local
http://localhost:4004/library/Books?$search=harry&$count=true


###
#create book
POST http://localhost:4004/library/Books
OData-Version: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json

{
    "title": "kevin 124",
    "subtitle": "some subtitle",
    "source": "library database"
}

###
#update book
PATCH http://localhost:4004/library/Books(271)
OData-Version: 4.0
Content-Type: application/json;odata.metadata=minimal
Accept: application/json

{
"title" :  "kevin's cosmeticology"
}


###
#delete book
DELETE http://localhost:4004/library/Books(1)


###
#filter
GET http://localhost:4004/library/Books?$filter=contains(title,'wu')